export const AUTH_INITIALIZATION_DONE = 'AUTH_INITIALIZATION_DONE';
export const AUTH_LOGGED_OUT_SUCCESS = 'AUTH_LOGGED_OUT_SUCCESS';
export const AUTH_LOGGED_IN_SUCCESS = 'AUTH_LOGGED_IN_SUCCESS';

export const MODAL_TRIGGER_TRUE = 'MODAL_TRIGGER_TRUE';
export const MODAL_TRIGGER_FALSE = 'MODAL_TRIGGER_FALSE';
